# -*- coding: utf-8 -*-
"""Language detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r31r6nt6f2SIDKP90LIwwBZspwpqv93d
"""

import string
import pandas as pd
import numpy as np
import re
import matplotlib as plt
import seaborn as snb

df = pd.read_csv('Language Detection.csv')
df.head()

"""## Cleaning up"""

def remove_pun(text):
  for p in string.punctuation:
    text=text.replace(p,"")
  text=text.lower()
  return text

testing = "Sathvik is a good Boy!!"

remove_pun(testing)

df['Text']=df['Text'].apply(remove_pun)
df

from sklearn.model_selection import train_test_split

X = df.iloc[:,0]
Y = df.iloc[:,1]

X_train,X_test, Y_train,Y_test = train_test_split(X,Y, test_size=.3)



from sklearn  import feature_extraction

vec = feature_extraction.text.TfidfVectorizer(ngram_range=(1,2), analyzer='char')

from sklearn import pipeline
from sklearn import linear_model

model_p = pipeline.Pipeline([('vec',vec),('clf',linear_model.LogisticRegression())])

model_p.fit(X_train,Y_train)

pred = model_p.predict(X_test)

from sklearn import metrics

metrics.accuracy_score(Y_test,pred)*100

metrics.confusion_matrix(Y_test,pred)

model_p.predict(["ಶಿಕ್ಷಣಕ್ಕೆ ಪ್ರತಿಯೊಬ್ಬನಿಗೂ ಹಕ್ಕುಂಟು ಶಿಕ್ಷಣವು ಕೊನೆಯ ಪಕ್ಷಪ್ರಾ ಥಮಿಕ ಹಾಗೂ ಮೂಲ ದರ್ಚೆಗಳಲ್ಲಿ ಧರ್ಮಾರ್ಥವಾಗಿರಬೇಕು. ಪ್ರಾಥಮಿಕ ಶಿಕ್ಷಣವು ಕಡ್ಡಾ ಯವಾಗಿರಬೇಕು. ಶಿಲ್ಪ ಶಿಕ್ಷಣ ಹಾಗೂ ವೃತ್ತಿಶಿಕ್ಷಣಗಳು ಸಾಮಾನ್ಯ ವಾಗಿ ಒದಗಿಸಲಾಗುವುವು. ಮತ್ತು ಉಚ್ಚ ಶಿಕ್ಷಣವು ಯೋಗ್ಯತೆಯ ಮೇಲೆ ಸರ್ವರಿಗೂ ಸಮಾನವಾಗಿ ದೊರೆಯಲಾಗುವುದು."])

import pickle

new_file = open('model.pckl','wb')
pickle.dump(model_p,new_file)
new_file.close()

open('app.py','w')



import os
os.listdir()

!pip install streamlit

!streamlit run app.py & npx localtunnel --port 8501

!npm install -g localtunnel

